server:  
  port: ${PORT:0}
  error:    
    include-message: always


spring:
  application:    name: ms-profile
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: ms-profile

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration     

## EUREKA
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka
      
# CONFIG SERVER PROBLEMAS AL DOCKERIZAR
#  cloud:
#    config:
#      uri: http://config-server:8888
#      fail-fast: true
#      retry:
#        max-attempts: 20
#        max-interval: 15000
#        initial-interval: 10000
#    